databases:
  - name: postgres
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: Joker
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 jep.py & bash start
    region: frankfurt
    repo: https://github.com/jepthoniq/lMl10l      
    branch: 313
    envVars:
      - key: ALIVE_NAME
        sync: false
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: ENV 
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_USERNAME
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.5
      - key: TZ
        value: Asia/Baghdad 
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString   
    autoDeploy: false
